{
 "title": "PyFusionSolarDataRelay Dashboard",
 "description": "Dashboard for PyFusionSolarDataRelay InfluxDBv2 data",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Current solar power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fusionsolar\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"site01\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"realTimePower\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: r._value / float(v:1000)}))\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Solar energy lifetime total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fusionsolar\")\r\n  |> range(start: -99999d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"site01\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cumulativeEnergy\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n  "
    }
   ]
  },
  {
   "title": "Generated solar energy 12 hours",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"fusionsolar\")\r\n  |> range(start: -12h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"site01\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cumulativeEnergy\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n  |> difference(\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    keepFirst: false,\r\n    initialZero: false,\r\n  )\r\n  "
    }
   ]
  },
  {
   "title": "Generated solar energy 30 days",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"fusionsolar\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"site01\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cumulativeEnergy\")\r\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\r\n  |> difference(\r\n    nonNegative: true,\r\n    columns: [\"_value\"],\r\n    keepFirst: false,\r\n    initialZero: false,\r\n  )\r\n  "
    }
   ]
  }
 ]
}