{
 "title": "PV-installatie Xibo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Opgewekte zonne-energie",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum by (time) (\r\n  increase(energy_liftetime_energy_wh{db=\"fusionsolar\", data_source=\"kiosk_realkpi\", site_descriptive_name=\"my_site\", measurement_type=\"station\", station_dn=\"NE=140991234\"}[$__rate_interval])\r\n)",
     "legendFormat": "Installatie1"
    }
   ]
  },
  {
   "title": "Actueel vermogen pv-panelen",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(energy_real_time_power_w{db=\"fusionsolar\", data_source=\"kiosk_realkpi\", site_descriptive_name=\"my_site\", measurement_type=\"station\", station_dn=\"NE=140991234\"}[$__interval]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Totale opwek pv-panelen",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (time) (\r\n  447200000 + last_over_time(energy_liftetime_energy_wh{db=\"fusionsolar\", data_source=\"kiosk_realkpi\", site_descriptive_name=\"my_site\", measurement_type=\"station\", station_dn=\"NE=140991234\"}[1h])\r\n) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}